### ISSUE TITLE
无法引导

### ISSUE THREAD

**Issue by Vtiger007** [JackCHENxx/Dell-Optiplex-3046-MFF-hackintosh-EFI#1]
1.硬件是一样的。
2.用的是小兵大神的三分区安装包
3.替换原包中OC下的EFI。
4.用OC无法引导。
5.改用Clover引导，糊里糊涂的安装成功了。
6.现在用Clover引导可以进入系统，体验一般，后续调整优化正在学习中。

**Comment by LoganD19** [comment]
I am having the same boot issue. Going to try what you suggested with the Clover install
