### ISSUE TITLE
Airdrop Suggestion

### ISSUE THREAD

**Issue by gatorback** [JackCHENxx/Dell-Optiplex-3046-MFF-hackintosh-EFI#2]
Hi Jack,

Thank you for posting your EFI. 

AirDrop requires a Broadcom Wifi / Bluetooth device such as the Dual Band Wireless Broadcom BCM94360NG M.2 WiFi Bluetooth Card 802.11ac.   https://www.ebay.com/itm/283934768547

I replaced my Intel wifi with the BCM94360NG M.2 WiFi Bluetooth Card (no kexts required) and AirDrop works.   Hope this is helpful.

Does your 3046 work in 4K?  DisplayPort?   I tested your EFI in a Dell Optiplex 7050 Micro i5-6500T 2.50GHz and was not successful.  https://www.ebay.com/itm/195410360637

**Comment by JackCHENxx** [comment]
Hi Raymond,
I have only 2K screen available, Never tested with 4K, theoretically if you modified DVMT in BIOS to 128MB, it should work with 4K.

BR

在 2022年12月19日，11:52，Raymond Chiu ***@***.***> 写道：

﻿

Hi Jack,

Thank you for posting your EFI.

AirDrop requires a Broadcom Wifi / Bluetooth device such as the Dual Band Wireless Broadcom BCM94360NG M.2 WiFi Bluetooth Card 802.11ac. https://www.ebay.com/itm/283934768547

I replaced my Intel wifi with the BCM94360NG M.2 WiFi Bluetooth Card (no kexts required) and AirDrop works. Hope this is helpful.

Does your 3046 work in 4K? DisplayPort? I tested your EFI in a Dell Optiplex 7050 Micro i5-6500T 2.50GHz and was not successful. https://www.ebay.com/itm/195410360637
